version: '3.8'

services:
  # SERVICE 1: Web server + Backend API (Aset frontend sudah melekat utuh di dalam image ini)
  web_backend_laravel:
    image: ghcr.io/bachtiarja/sehati-web:latest
    container_name: web_backend_laravel
    restart: always
    ports:
      - '8000:80' # Mengakses port 8000 pada VPS akan langsung direspons Nginx internal container
    env_file:
      - .env
    volumes:
      - ./storage:/var/www/html/storage
    depends_on:
      - db_kelompok30

  # SERVICE 2: Database MySQL (Nama service disamakan dengan container name agar DB_HOST aman)
  db_kelompok30:
    image: mysql:8.0
    container_name: db_kelompok30
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=sehati_db
    volumes:
      - db_data:/var/lib/mysql

  # SERVICE 3: phpMyAdmin (UI untuk Database)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: sehati_phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=db_kelompok30 # Sesuai dengan nama service database di atas
      - PMA_PORT=3306
    restart: unless-stopped
    depends_on:
      - db_kelompok30

volumes:
  db_data:
