name: Deploy to VPS

on:
  push:
    branches:
      - main # Jalankan otomatis setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository kodingan
        uses: actions/checkout@v4

      - name: Eksekusi Perintah di VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Pindah ke folder project di VPS (buat jika belum ada)
            mkdir -p ~/app-web && cd ~/app-web

            # Jika menggunakan Git di VPS untuk sinkronisasi kode:
            # git pull origin main

            # Perintah untuk mendeploy menggunakan docker compose
            # docker compose up -d --build
