name: Production CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  # DIPAKSA LOWERCASE: Langsung hardcode nama repo dengan huruf kecil agar GHCR tidak error
  IMAGE_NAME: bachtiarja/sehati-web

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Setup Node.js untuk kompilasi Frontend di dalam Cloud Runner
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Jalankan kompilasi aset Vite murni di server GitHub
      - name: Compile Frontend Assets (Vite)
        run: |
          npm install
          npm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-vps:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/Kelompok30/sehati-web
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            docker compose pull
            docker compose up -d --remove-orphans
            
            # Otomatisasi pembersihan internal state Laravel pasca deploy luar
            docker exec web_backend_laravel php artisan migrate --force
            docker exec web_backend_laravel php artisan view:clear
            docker exec web_backend_laravel php artisan config:clear
            docker logout ghcr.io